---
- hosts: webserver
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
     - name: copying the php file
       copy:
         src: /home/ansible/index.php
         dest: /var/www/html/index.php
         force: yes 
