---
- name: Install MySQL
  hosts: webserver
  become: true
  remote_user: root
  become_method: sudo
  gather_facts: true
  
  tasks:
    - name: "Installing Repo"
      shell: sudo rpm -Uvh http://repo.mysql.com/get/mysql-community-release-el7-7.noarch.rpm
      ignore_errors: yes
    - name: "Installing MySQL 5.7"
      package: name=mysql-community-server state=present
    - name: Start the MySQL service
      become: true
      service:
        name: mysqld
        state: started
        enabled: true
