---
- name: myfirstplaybook
  hosts: webserver
  
  task:
    - name: make sure apache is at the latest version
      yum:
        name: httpd
        state: latest

    - name: ensure apache is running
      service:
        name: httpd
        state: started
